### ISSUE TITLE
Attribute rippleColor is defined in the new design support library

### ISSUE THREAD

**Issue by SudaNix** [navasmdc/MaterialDesignLibrary#274]
rippleColor attribute is now defined on the new design support library ('com.android.support:design:22.2.0')
https://android.googlesource.com/platform/frameworks/support/+/android-m-preview/design/res/values/attrs.xml

So we cannot use this library and the design library in the same time.
Any suggestion?

**Comment by Spiderbezno** [comment]
I have the same problem??

**Comment by dhavaln** [comment]
Same issue for me.

**Comment by sharezz** [comment]
I imported MaterialDesignLibrary into my project as a library and changed the "rippleColor" attribute name. It works now with new design support library. It can be a temporary solution.

**Comment by navasmdc** [comment]
Uffff, it is a bad issue, this change will effect to all users.
I will change the attribute name in the next version and i will notify  this change to the all users.
Thanks!

**Comment by dawidhyzy** [comment]
Same issue for me.

**Comment by EliasMazz** [comment]
Same Here

**Comment by tiago7s** [comment]
This library is widely used. Because of this I have to download your project and make the change or simply stop using this library. Please add a namespace to your attributes or simply change this single one quickly.

**Comment by conzorz** [comment]
Yeah dude, if someone could just change this to RippleColor or something, we'd love you forever!

**Comment by ecr24** [comment]
Same issue... :(

**Comment by Shashank066** [comment]
I have the same issue. Please fix it asap.

**Comment by CedricVandelaer** [comment]
The library is great, but please fix this issue, it's pretty essential to my app :/

**Comment by sohayb** [comment]
+1

**Comment by javiersantos** [comment]
Please fix as soon as possible. I use this library a lot :(

**Comment by perpetuatingcuriosity** [comment]
@navasmdc Is there an ETA on when this might be fixed? I’d like to use it in a beta apk release at the end of the month.

**Comment by Spiderbezno** [comment]
are there any solution??

**Comment by muhammad-naderi** [comment]
any plan for fixing this?!

**Comment by ragasjohn** [comment]
Same here!

**Comment by devv** [comment]
me too..Any luck?

**Comment by Informatheus** [comment]
Same problem, i had to stop using this lib cause i need com.android.support:design:22.2.1.

**Comment by ragasjohn** [comment]
I remove it also....too pity

**Comment by Hakosuka** [comment]
I'm getting this problem too.

**Comment by kosiara** [comment]
I'm facing the same problem: 

Error:(2) Attribute "rippleColor" has already been defined

when adding the new library
 compile 'com.android.support:design:22.2.1'

**Comment by kosiara** [comment]
I've compiled a version which can be used alongside support design library
(eliminates Attribute "rippleColor" has already been defined error) :

compile 'com.android.support:design:22.2.1'

changes:
https://github.com/kosiara/MaterialDesignLibrary/commit/e94c9f37bf427d5d90bc8771357296fc36d9b2d8

binary aar file:
https://github.com/kosiara/MaterialDesignLibrary/raw/e3a94ec606062eeb3ae2421a119cd729c43fee76/compiled-versions/MaterialDesign-md_ready-release.aar

**Comment by bingo4508** [comment]
Same Problem!

**Comment by ibamadd** [comment]
anyway we can exclude any repeated resources I'm having a similar issue with `color.xml` and `values`...

**Comment by niwinnm** [comment]
I have modified the attribute "rippleColor" to "mRippleColor"

Have forked the current version in here: https://github.com/vajro/MaterialDesignLibrary

**Comment by blackvvine** [comment]
@niwinnm Thanks, is it normal that minimum SDK is 16? can't it be set to 15?

**Comment by niwinnm** [comment]
Well, I simply forked the version and altered the rippleColor attribute. The minimum SDK should be same as the parent version.

**Comment by jakewilson801** [comment]
Does anyone know why this isn't being merged in? @tianzhijiexian @navasmdc are you guys done maintaining this?

**Comment by blackvvine** [comment]
Well there aren't many people on 15 anyway, but I always thought the library worked on SDK 15 :-)

**Comment by Zapnologica** [comment]
Has this problem been resolved in the latest version? I am also getting this error as I want to use floating label from android support library, How do I go about solving this issue?

**Comment by Tourenathan-G5organisation** [comment]
@niwinnm i have problem when am using **compile 'com.github.vajro:MaterialDesignLibrary:1.6'** . It gives mw an error which says *Failed to resolve: com.github.vajro:MaterialDesignLibrary:1.6*
What can i do to resolve this?

**Comment by niwinnm** [comment]
@Zapnologica - I renamed the attribute rippleColor to remove this issue. You could use my forked version instead.

https://github.com/vajro/MaterialDesignLibrary

**Comment by taar1** [comment]
Thanks niwinnm for the fork.
However, it's kind of shocking that this obvious bug still hasn't been fixed by the creators of this library!

**Comment by daveamol** [comment]
Having the same issue. Using @niwinnm repo fixed it although have to use minimum API version as 16
